version: '3'
services:
  postgres:
    image: postgres
    container_name: postgresDB
    restart: always
    environment:
      - POSTGRES_USER=myusername
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - data:/data
    ports:
      - 5432:5432
    networks:
      - mynetwork
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 8090:80
    networks:
      - mynetwork


#  java-api:
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    ports:
#      - 8090:8090
#    container_name: java-api
#    depends_on:
#      - postgres
#    networks:
#      - mynetwork
#    links:
#      - postgres


volumes:
  data: {}

networks:
  mynetwork: