version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    command:
      - --noauth
    ports:
      - 27017:27017
    volumes:
      - data:/data
    networks:
      external-shared-network:
  ticketing:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    container_name: ticketingAPI
    depends_on:
      - postgres
    networks:
      external-shared-network:
#    networks:
#      - mynetwork
    links:
      - postgres
  postgres:
    image: postgres
    container_name: postgres
#    restart: always
    environment:
      - POSTGRES_USER=myusername
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - data:/data
    ports:
      - 5432:5432
    networks:
      external-shared-network:
#    networks:
#      - mynetwork
  pgadmin:
    image: dpage/pgadmin4
#    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 8090:80
    networks:
      external-shared-network:
#    networks:
#      - mynetwork


volumes:
  data: {}

networks:
  external-shared-network:
    name: sharednetwork
    external: true
#  mynetwork:

