version: '3.8'
services:
  ticketing:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    container_name: ticketingAPI
    environment:
      - idprovider_api_url=http://java-api:8080/
    depends_on:
      - postgres
    networks:
      external-shared-network:
    links:
      - postgres
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=myusername
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - data:/data
    ports:
      - 5432:5432
    networks:
      external-shared-network:
  java-api:
    image: idprovider-java-api:latest
    ports:
      - 8080:8080
    container_name: java-api
    depends_on:
      - mongodb
    networks:
      external-shared-network:
    links:
      - mongodb
  mongodb:
    image: mongo
    container_name: mongodb
    command:
      - --noauth
    ports:
      - 27017:27017
    volumes:
      - data:/data
    networks:
      external-shared-network:
#  pgadmin:
#    image: dpage/pgadmin4
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
#      - PGADMIN_DEFAULT_PASSWORD=admin
#    ports:
#      - 8090:80
#    networks:
#      external-shared-network:


volumes:
  data: {}

networks:
  external-shared-network:
    name: sharednetwork
    external: true


